export const showTranslationBtn = 'Show translations'
export const firstListItemClassName = 'word-item'
export const nextBtnClassName = 'btn btn-success'
export const nextBtnCaption = 'Next'
export const wordCardBtnClassName = 'btn btn-outline-secondary'
export const defaultClass = 'class4'
export const defaultSearchType = 'translation'
export const baseRoute = '/learn-hebrew/'
